name: WTP
main: cc.isotopestudio.WTP.WTP

author: Mars
description: Public Teleportion
website: http://isotopestudio.cc
version: 1.1.1
depend: [Vault]
commands:
  wtp:
    description: 公共地标玩家管理菜单
    usage: /<command>
  wlist:
    description: 公共地标列表
    usage: /<command>
  w:
    description: 传送到
    usage: /<command>
  wtpadmin:
    description: 公共地标管理员菜单
    usage: /<command>